### PR TITLE
Bug Fix Android Modal Crash

### LINKED ISSUE #14: Android Admin Invite and Update Modals Crash Application
**Describe the bug**
When logged in as an Admin on Android opening the Invite or Update modal causes the app to crash.

**To Reproduce**
1. Login
2. In Home view switch to Admin tab
3. Click Floating Action Button or Edit Icon
4. See app crash

**Expected behavior**
App should no crash

**Screenshots**
White screen

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android

### PR DESCRIPTION
**Pull request by NickHackman**
Resolves: #14

## Summary

The reason the modals crashed on Android was because of the View that
had a margin of 5, which was effectively a divider. Switched to Dialogs
for displaying this content as it looks better than using Modals. Also moved the larger Modals into their own files as they were full on components. They had formik hooked in and their own operation so it seemed like a good idea to separate them.

## Acceptance Criteria

- [x] No longer broken

### New Invite
windowshot-12-05-2020-02:36:50 AM

### New Edit
windowshot-12-05-2020-02:36:40 AM

### CODE REVIEW

File: src/views/Home/Admins.tsx [hunk 1]
```diff
@@ -1,127 +1,57 @@
...
-    const { name, email } = fields;
-    try {
-      Admin.update(email, name, props.token);
-      setEditModal(false);
+      await Admin.delete(selectedAdmin.email, token);
       onRefresh();
-    } catch {
-      // TODO: show error message
+    } catch (err) {
+      onErr(err.toString());
```
Comment (freeman91) [inline src/views/Home/Admins.tsx:51]: thanks for picking these up

**Review by freeman91 — APPROVED** [review]
